### PR TITLE
Doc: add 2 traitsui examples

### PR DESCRIPTION
**Pull request by jonathanrocher**
- Splitting the existing examples into `enaml_based` and `traitsui_based`. 
- Ported 2 examples to traitsUI (counties and web) to demo loading tiles from local file and remotely even for people who don't have `enaml`.
- Moved shared data files to a new `data` folder
- A few `flake8` fixes here and threre. Enaml folder still isn't flake8.

### CODE REVIEW

**Comment by jonathanrocher** [comment]
@andrewcollette Could you take a look?

**Comment by andrewcollette** [comment]
The TraitsUI demos work fine for me.  Btw, here's the server information I used to replace the tile cache in my own copy of the `chaco_map.py` demo:

```
tile_cache = HTTPTileManager(server='otile1.mqcdn.com',url='/tiles/1.0.0/map/%(zoom)d/%(row)d/%(col)d.jpg')
```

**Comment by pberkes** [comment]
I merge master to fix PIL.
I tried the TraitsUI examples, they work great.

**Comment by jonathanrocher** [comment]
I am going to consider 2 external testers for this is enough. Merging...

**Pull request merged**
