### PR TITLE
Fix enaml examples

### PR DESCRIPTION
**Pull request by jwiggins**
~~This is based on two earlier PRs, so it can't go in yet.~~

The enaml examples were a bit out of date. This brings them up-to-date with enaml 0.9.8 (and likely 0.10.X as well, but that's not tested).

### CODE REVIEW

**Comment by senganal** [comment]
The enaml errors have gone away but some of the examples do not display a map as the default server seems to be mapquest for the enaml examples.  It would be good to update that, so that the examples are functional..

**Comment by jwiggins** [comment]
Thanks for checking. I rebased to get the fixes from #16 and then made sure the HTTP-using examples work.

**Comment by senganal** [comment]
Thanks.. LGTM..

**Comment by senganal** [comment]
@jwiggins Why rebase the branches ? Its kinda a pain to update local branches when reviewing.. the recommended policy is to never rebase once a branch has been shared with others.. merging master onto the branch works just fine.. no ?

**Comment by jwiggins** [comment]
Sorry for the pain, it's a habit that I picked up when working with Gitlab (which handles such a workflow more elegantly).

**Comment by jwiggins** [comment]
Thanks for the review/feedback!

**Pull request merged**
